# Generated by Django 3.1.1 on 2020-09-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20200930_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=': الاسم')),
                ('telephone', models.CharField(max_length=40, verbose_name=': رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=50, verbose_name=': العنوان')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'انثي')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.profile')),
            ],
        ),
    ]
