# Generated by Django 3.1.1 on 2020-09-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20200930_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='clinic',
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'clinic', 'verbose_name_plural': 'clinics'},
        ),
    ]
