# Generated by Django 3.1.1 on 2020-10-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_auto_20201001_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='services',
            field=models.CharField(max_length=4000, verbose_name='الخدمات المقدمه'),
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
