# Generated by Django 3.1.1 on 2020-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20201001_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(default=1, upload_to='clinic', verbose_name=': الصوره الخاصه بالعياده'),
            preserve_default=False,
        ),
    ]
