# Generated by Django 3.1.1 on 2020-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clinic', verbose_name=': الصوره الخاصه بالعياده'),
        ),
    ]
