# Generated by Django 3.1.1 on 2020-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_remove_clinic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
