# Generated by Django 3.1.1 on 2020-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='works_hour',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
