# Generated by Django 3.1.1 on 2020-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_auto_20201001_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='subtitle',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name=': نبذه عن العياده'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='services',
            field=models.CharField(max_length=2000, verbose_name='الخدمات المقدمه'),
        ),
    ]
