# Generated by Django 3.1.1 on 2020-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_auto_20201001_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='Email',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name=': الايميل:'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='facebook',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=': لينك صفحه الفيسبوك'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='twitter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=': لينك تويتر '),
        ),
    ]
