# Generated by Django 3.1.1 on 2020-10-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_auto_20201001_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
