# Generated by Django 3.1.1 on 2020-10-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_clinic_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='name',
            new_name='clinic_name',
        ),
    ]
