# Generated by Django 3.1.1 on 2020-10-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_auto_20201002_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_name',
            new_name='name',
        ),
    ]
