# Generated by Django 3.1.1 on 2020-10-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='password',
        ),
    ]
