# Generated by Django 3.1.1 on 2020-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0024_remove_clinic_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='services',
            field=models.CharField(max_length=4000, verbose_name='الخدمات المقدمه'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=': نبذه عن العياده'),
        ),
    ]
