# Generated by Django 3.1.1 on 2020-10-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0028_auto_20201003_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinc_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
