# Generated by Django 3.1.1 on 2020-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0030_clinic_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='address',
        ),
        migrations.AddField(
            model_name='clinic',
            name='type_of_person',
            field=models.CharField(choices=[('alex', 'الاسكندريه'), ('cairo', 'القاهره'), ('matroh', 'مطروح'), ('aswan', 'اسوان')], default=1, max_length=15, verbose_name='المحافظه'),
            preserve_default=False,
        ),
    ]
