# Generated by Django 3.1.1 on 2020-10-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0031_auto_20201004_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='type_of_person',
            new_name='type_of_city',
        ),
    ]
