# Generated by Django 3.1.1 on 2020-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0033_auto_20201004_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='comment',
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='الايميل'),
        ),
    ]
