# Generated by Django 3.1.1 on 2020-10-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0036_auto_20201005_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(default=1, max_length=2000, verbose_name='الايميل'),
            preserve_default=False,
        ),
    ]
