# Generated by Django 3.1.1 on 2020-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انثي')], default=1, max_length=5, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
