# Generated by Django 3.1.1 on 2020-10-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_type_of_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_city',
            field=models.CharField(choices=[('alex', 'الاسكندريه'), ('cairo', 'القاهره'), ('matroh', 'مطروح'), ('aswan', 'اسوان')], default=1, max_length=15, verbose_name='المحافظه'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='city',
        ),
    ]
