# Generated by Django 3.1.1 on 2020-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201005_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name=': الصوره البطاقه الشخصيه'),
        ),
    ]
