# Generated by Django 3.1.1 on 2020-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201009_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='profile', verbose_name=': الصوره البطاقه الشخصيه'),
            preserve_default=False,
        ),
    ]
