# Generated by Django 3.1.1 on 2020-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201009_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='profile', verbose_name=': الصوره البطاقه الشخصيه'),
        ),
    ]
